{"name": "test_login_with_invalid_credentials_error[nonexistent_user@example.com-wrongpassword123]", "status": "passed", "parameters": [{"name": "email", "value": "'nonexistent_user@example.com'"}, {"name": "password", "value": "'wrongpassword123'"}], "start": 1736196509573, "stop": 1736196509807, "uuid": "12696af2-8e0b-46cb-bc15-a866b0613983", "historyId": "5a01555a1bcccddfb3fb6fd8bcd9a2df", "testCaseId": "6b9d0b2bbcc52e9a323a7a861fe1fa3b", "fullName": "tests.test_user_login.TestLoginUser#test_login_with_invalid_credentials_error", "labels": [{"name": "story", "value": "Логин с неверными данными"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "Oxanas-MacBook-Pro.local"}, {"name": "thread", "value": "90867-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}