{"name": "test_login_with_invalid_credentials_error[-password123]", "status": "passed", "parameters": [{"name": "email", "value": "''"}, {"name": "password", "value": "'password123'"}], "start": 1736196509813, "stop": 1736196510121, "uuid": "601f8d3c-90ff-4956-be61-f06008b5997e", "historyId": "8506da5cf02c38ba0a64a116c0bbaab6", "testCaseId": "6b9d0b2bbcc52e9a323a7a861fe1fa3b", "fullName": "tests.test_user_login.TestLoginUser#test_login_with_invalid_credentials_error", "labels": [{"name": "story", "value": "Логин с неверными данными"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "Oxanas-MacBook-Pro.local"}, {"name": "thread", "value": "90867-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}